# Generated by Django 3.0.5 on 2020-11-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0002_club_intro'),
    ]

    operations = [
        migrations.CreateModel(
            name='lecture_rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.CharField(max_length=30)),
                ('teacher', models.CharField(max_length=10)),
                ('rate', models.FloatField()),
                ('semester', models.CharField(max_length=10)),
                ('context', models.CharField(max_length=1000)),
            ],
        ),
    ]
