# Generated by Django 3.0.5 on 2020-11-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus_To_School_From_Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField(default=0)),
                ('minite', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Bus_To_School_From_Station_Sunday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField(default=0)),
                ('minite', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Bus_To_Station_From_School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField(default=0)),
                ('minite', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Bus_To_Station_From_School_Sunday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField(default=0)),
                ('minite', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='BlogData',
        ),
    ]
