# Generated by Django 3.0.5 on 2020-11-21 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0003_career_notice_common_notice_corona_action_notice_corona_prevent_notice_event_notice_scholarship_noti'),
    ]

    operations = [
        migrations.CreateModel(
            name='weekly_menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200)),
            ],
        ),
    ]
