# Generated by Django 3.0.5 on 2020-11-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('place', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=255)),
            ],
        ),
    ]
